footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_layer:
    observation_sources: laser_sensor point_cloud_sensor
    laser_sensor: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}
  # assuming receiving a cloud from rtabmap_ros/obstacles_detection node
    point_cloud_sensor: {
      sensor_frame: zed2_camera_center,
      data_type: PointCloud2, 
      topic:  /rtab_zed2/local_grid_obstacle,
      expected_update_rate: 500, 
      marking: true, 
      clearing: true,
      min_obstacle_height: 2,
      max_obstacle_height: 99999.0}



inflation:
    inflation_radius: 3.0
